### ISSUE TITLE
Smithing Template, Netherite Upgrade

### ISSUE THREAD

**Issue by mit999sif** [Leronus/mOres#15]
Hi, I can't find the Netherite Upgrade Treasure chest with a 100% of possibilities, I just find the obsidian upgrade.

**Comment by Leronus** [comment]
> Hi, I can't find the Netherite Upgrade Treasure chest with a 100% of possibilities, I just find the obsidian upgrade.
> 
> 
> 

Hey mitsif,

Thanks for informing me with this issue.
I'll do some testing to see if I can reproduce the issue. 

I'm assuming you're using the latest version for 1.20.1, correct?

What chests specifically did you expect to find the netherite upgrade? It's been a little while since I've messed around with the loot tables.

I'll keep you posted with any updates.

**Comment by mit999sif** [comment]
Hi, yes it's the 1.20.1 version, i got the information form https://minecraft.fandom.com/wiki/Smithing_Template, supposedly you can find them in the bastion chest, 10% of probability  in the normal ones and 100% on the Treasure chest.

**Comment by Leronus** [comment]
Gotcha. You were right, it was spawning way less frequent than it was supposed to. 
I have updated the loot tables and they should now spawn as per the vanilla values described in https://minecraft.fandom.com/wiki/Smithing_Template, as you mentioned.

You may download the update [**here**](https://legacy.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4779964).

Thanks again for playing my mod, hope this has solved your issue ❤️

**Comment by mit999sif** [comment]
Thank you, I really like your work! Great job
