### ISSUE TITLE
Adding mod to aternos

### ISSUE THREAD

**Issue by Dogy1705** [Leronus/mOres#24]
First off all I am sorry for asking this question here, but due to the links to your discord not working I had to come here to ask this question. As the title says I’m trying to add your amazing mod to aternos (just in case aternos is a server provider so yeah) I been trying to add your mod to my 1.20.4 server with my friends but since apparently the mod isn’t open for distribution outside of forge and overwolf, aternos isn’t able to add the mOers mod to the server; So I wanted to ask I know it maybe asking to much if you can make it open for distribution outside of forge so aternos can be able to add the mod to the server; if you have the time to answer it would be greatly appreciated

**Comment by Magmazzzz** [comment]
hey dude

did you find it on aternos?

**Comment by Leronus** [comment]
I have had many questions about this before, sadly the answer is still no. I'll make sure to add it to the FAQ on the project page.
I do apologise. The reason is because I am able to do this solo and on the side, because of the rewards program. Any downloads outside of CurseForge will not count. Perhaps through a donation system I could consider it but for the foreseeable future this is unlikely.
