### ISSUE TITLE
Crafting not working in 1.20.4

### ISSUE THREAD

**Issue by Rognvaldir** [Leronus/mOres#26]
Don't know if it is because of the cracked Minecraft or the plethora of mods added (150) but i cannot craft anything at the Crafting Table.  I tried to craft a Tin and Silver Shovel and it does not work
Proof: 
![2024-03-14_00 19 01](https://github.com/Leronus/mOres/assets/163406500/35216410-ccb8-471f-b0ed-17423a4ad7dc)

**Comment by Leronus** [comment]
I've tried to reproduce the issue but was unable to do so.
I can only speculate as to why it's not working, because I'd need the mod list and logs to know more.
With this information I can only conclude it must be caused by one of the mods added, considering you mentioned there are about 150 mods.

Sorry for the somewhat slow reply, life has been busy for me.
Thanks for playing my mod and I'm sorry you're encountering issues.
My personal recommendation would be to remove mods one by one to see which ones are causing issues. It's a slow and tedious process but unfortunately the only way I can think of.

Kind regards,
Leronus

![Screenshot 2024-03-17 041635](https://github.com/Leronus/mOres/assets/7829958/bad77e31-178f-4909-bbc5-42ca525f0367)

**Comment by Rognvaldir** [comment]
Don't know if it's ok to respond to a closed issue, sorry if it isn't. I have found what the issue was. The Game Rule "Require Recipe to craft" was enable and it did not allowed me to craft, while deactivating it worked. And in both instances, after obtaining the Ingot for the recipes, none would appear on the Crafting Book for quick craft, you must craft manually. If it's intented like that sorry for the confusion
