### ISSUE TITLE
Crashes with and without Better Shields

### ISSUE THREAD

**Issue by Lartza** [Leronus/mOres#6]
Running just mOres and JEI the game will crash when creating a world seemingly looking for Better Shields.

Crash report and log without Better Shields
https://gist.github.com/Lartza/5e2828cb4755cc6be13563b89ed695af

Adding Better Shields crashes the game at launch instead.

No crash report generated just log
https://gist.github.com/Lartza/e8664037ef734b653472f6bfba10d376

Forge 40.1.31
mOres 3.0.4
JEI 9.5.5.174
Better Shields 1.0.1

**Comment by Leronus** [comment]
Dear @Lartza 

Thank you for bringing this issue to my attention. After some testing I have identified the issue lies with a compatibility problem with JEI. It is definitely on my side, meaning I have yet to make this mod more compatible with other mods.

For now simply playing without JEI will stop the crashing, in the meantime I will try and fix this compatibility issue so you can play this mod with any other mod you like. Please note I am a beginner and that is why I have not yet perfected this mod to work as intended.

I will update you with any progress made, if you'd like to contact me my discord is: Leronus#0830

Thanks again!
Kind regards,
Leronus

**Comment by Leronus** [comment]
Hey man, 

I'm happy to inform you that I have already fixed the issue.
Please download the updated version of mOres (v3.0.5)
You should now be able to use mOres with JEI.
BetterShields is not required in any way.

Kind regards,
Leronus

**Comment by Lartza** [comment]
I can confirm the main issue with JEI is no longer an issue, but the crash with Better Shields (without JEI) still remains if you some day want to fix that https://gist.github.com/Lartza/8fd9f390db454d5ec169c2fa1c275ab1

It's pretty much a different issue completely though, and don't worry you take your time fixing your mod you don't owe a deadline to anyone. I'm not even personally interested in playing with your mod just helped someone report the JEI issue by reproducing.

And we all have to be beginners at everything once to get better :)
